### ISSUE TITLE
less hacky way to execute functions

### ISSUE THREAD

**Issue by cravxx** [HulaSamsquanch/aimgames#11]
currently they only execute on enter keypress.

**Comment by cravxx** [comment]
This issue was moved to HulaSamsquanch/swearify#2

**Comment by uwx** [comment]
i fixed the functions for the new chatbox (actually i haven't since the script is expected to be run from the iframe but thats a quick fix), but its still doing it the hacky way
the right way to do it i think would be to make _the entire script_ be injected onto the page (like the chatbox is)
one way to do this without fucking everything up and forcing us to do stupid escaping bullshit every time we want to update is to do it like this
`a = function() {return "derp";}`
now if you use `console.log(''+a);` for example, you will get the entire function as a string without needing to escape it or anything like that (since we're not dealing with regex for example)

**Comment by uwx** [comment]
ok, i've revised the code and now it loads the script from an URL, so we don't need to do any hacky shit at all. only downside is that we need to use rawgit.com otherwise it won't serve the proper mime type and the script won't load.

**Comment by uwx** [comment]
this is now a problem again

**Comment by uwx** [comment]
may be fixable using input addeventhandler click

**Comment by uwx** [comment]
may also be fixable by hijacking and replacing the existing button

**Comment by uwx** [comment]
fixed by bbd0a6b5a0db71b084aeb926a18998c4564659ca (#54)
